### ISSUE TITLE
PLUGINS: Structure of folders (plugin-skel and plugins)

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#120]
I need some more background to the plugins and why their folder structure is different to the other apps: 

- Why are the plugin-skel/plugins folders outside of src?
- Why are the plugin-skel/plugins folders different in structure compared to the other apps (component.js holds both component and container code)?
- What is the plugin-skel folder? (and what is the equivalent in the Dashboard and Signup apps? is it DashboardMain and SignupMain? )
- Can ActionWrapper be considered its own app equivalent to Dashboard and Signup?
- Why does the plugin-skel and the two plugins each have their own stores?

> I actually really like this folder structure and it is very close to what I would like to do for the other separate apps. I'd like to keep the folders, but maybe make the filenames more specific.

**Comment by enriquepablo** [comment]
The idea was that we were going to want to add many more "action plugin" apps, like those we have atm for the ToU and MFA, so I wanted to streamline the development of new plugins and the build process for the whole of them.

The buildPlugins.js script reads the contents of the plugins directory and has a template string with webpack configuration, so the build process is independent of the amount and nature of the plugins within the plugins/ directory. Since it has a different build story than the main comonents inside src/, y took them out of src/, and put it at the same level as the companion  buildPlugins.js script.

The plugin-skel contains a skeleton for an "action plugin" app. When one is needed, plugin-skel/ is copied into the plugins/ folder and renamed, and the placeholders substituted with corresponding data. Then, buildPlugins.js will see it there and will build a bundle for it. This was originally meant to be a cookiecutter template - but adding the need for a Python env to the deveopment of the front did not seem worth it, and the skeleton contains very little code to check and fix.

**Comment by njons** [comment]
> The idea was that we were going to want to add many more "action plugin" apps, like those we  have atm for the ToU and MFA, so I wanted to streamline the development of new plugins and the build process for the whole of them.

- This overall idea sounds really good! Is it at all possible to do the same for the other apps we have? Provide a more streamlined process for starting the signup/login/dashboard apps, that perhaps diverge at specific points where the apps are different? Or does that not make sense?

> The buildPlugins.js script reads the contents of the plugins directory and has a template string with webpack configuration, so the build process is independent of the amount and nature of the plugins within the plugins/ directory. Since it has a different build story than the main comonents inside src/, I took them out of src/, and put it at the same level as the companion buildPlugins.js script.

- Will this folder structure make sense in the future as we develop the login app? If no, do we know how we want it to be structured in the future?

> The plugin-skel contains a skeleton for an "action plugin" app. When one is needed, plugin-skel/  is copied into the plugins/ folder and renamed, and the placeholders substituted with  corresponding data. Then, buildPlugins.js will see it there and will build a bundle for it. This was 
originally meant to be a cookiecutter template - but adding the need for a Python env to the deveopment of the front did not seem worth it, and the skeleton contains very little code to check and fix.

Does this mean that the plugin-skel is no longer in use or is it applied every time you trigger one of the actions (tou or mfa)?

**Comment by enriquepablo** [comment]
> Is it at all possible to do the same for the other apps we have?

In principle I wouldn't see much value in that. There is some repeated code, but it is boilerplate - code that is not changed. If we were to edit that code, I would agree about abstracting it away so we only edit it once. But while that does not happen, I think it is easier to understand and maintain as is.

I would say that there is enough difference in app initialization that providing a common procedure would complicate rather than simplify things.

> Will this folder structure make sense in the future as we develop the login app?

I don't see any reason why it wouldn't. The one thing I regret about plugins/ is not putting it under src/ (I always have to remember to grep in both src/ and plugins/). Other than that, I don't see any problem with the folder structure.

> Does this mean that the plugin-skel is no longer in use (...)

plugin-skel is never built - it is just the basic code common to all action plugins. It is only used when developing  a new action plugin, as a starting point: you copy the directory over to the plugins/ directory, change its name, and develop on top. Similar to the cookiecutter, but without automation.
