### ISSUE TITLE
PLUGINS: Naming of component file

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#121]
_plugin-skel/component.js_

- Is this the equivalent of SignupMain/DashboardMain?
- If so, can these files be renamed/refactored to align to the structure of the other apps?

> I actually really like this folder structure and it is very close to what I would like to do for the other separate apps. I'd like to keep the folders, but maybe make the filenames more specific.

**Comment by enriquepablo** [comment]
Since all pieces of each action plugin live in a common directory, naming them with the name of the plugin made no sense, that name was already in the containing folder, so I named them according to their contents.

Altering this structure will require altering the buildPlugins.js script that builds their bundles.
