### ISSUE TITLE
PLUGINS: Is the index.js file the same?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#123]
_plugin-skel/index.js_
_plugins/eduid_action.mfa/index.js_
_plugins/eduid_action.tou/index.js_

- Are the three ‘index.js’ files the same? 
- can they be refactored to reduce the number of files?

**Comment by enriquepablo** [comment]
These are "autogenerated files" (kind of, copied over) and the common stuff that they used to hold has been moved to entry-points/plugin-common; they have the barest content needed to call the init_plugin function. They might be abstracted away in some way so that the buildPlugins.js script would be able to find it and use it o build the different plugins, but I think it would be too much indirection for little gain.
