### ISSUE TITLE
PLUGINS: Multiple root sagas?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#125]
_plugin-skel/root-saga.js_
 _plugins/eduid_action.mfa/root-saga.js_
 _plugins/eduid_action.tou/root-saga.js_
 _src/plugin-saga.js_

What is the relationship between the above saga files?:
- Why are there separate action root-sagas and also a separate plugin root-saga? 
- Do they all act separately? 
- Could they be refactored?

**Comment by enriquepablo** [comment]
> _plugin-skel/root-saga.js_

This is the skeleton for the sagas specific for each plugin. When a new plugin is added, this is copied over.

> _src/plugin-saga.js_

This contains the saga configuration that is common to all plugins, imported from the specific root sagas (below) and used to build the correct root saga for each app. Since this is "library code" it is within src/

> _plugins/eduid_action.mfa/root-saga.js_

Sagas configuration specific for the MFA plugin; together with the common plugin-saga, it makes up the root saga for the MFA plugin

> _plugins/eduid_action.tou/root-saga.js_

Ditto for the ToU plugin.
