### ISSUE TITLE
PASSWORD RESET: Password reset flow when phone code has expired is aborted?

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-front#720]
#### Description of issue:
A bit long description... but
If I first request a new password, click on link in email and requests a OTP code that's being sent to my phone. 
Then I let that OTP code expire (+ 5min?).
Next: Restart a new reset password from start page, click link in reset email. I will be redirected back to start of reset password flow with status message "Phone code has expired. Please try again." (see picture). 

In this scenario I would expect to continue my password reset flow, since the first OTP already has timed out.

--- 
<img width="1116" alt="Skärmavbild 2021-09-19 kl  17 24 55" src="https://user-images.githubusercontent.com/36661180/133933203-d9b82972-deda-4208-8c0d-992391e19c72.png">

**Comment by ovesemart** [comment]
@johanlundberg @eunjuhuss 
Is this in staging? I still see the status message. The difference is that now I can proceed with the pw-reset.

**Comment by eunjuhuss** [comment]
@ovesemart 
I changed the path to redirect to "select extra security" page,
Since there are users with multiple extra security options available,  idea is that they have to actively chose how to proceed again...
maybe we should change the message to inform the users that they need to resend the phone code or chose an other option of extra security key
